// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: code-analyzer/code-analyzer.proto

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CodeAnalyzerServiceClient is the client API for CodeAnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeAnalyzerServiceClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type codeAnalyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeAnalyzerServiceClient(cc grpc.ClientConnInterface) CodeAnalyzerServiceClient {
	return &codeAnalyzerServiceClient{cc}
}

func (c *codeAnalyzerServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/codeanalyzer.CodeAnalyzerService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeAnalyzerServiceServer is the server API for CodeAnalyzerService service.
// All implementations must embed UnimplementedCodeAnalyzerServiceServer
// for forward compatibility
type CodeAnalyzerServiceServer interface {
	HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedCodeAnalyzerServiceServer()
}

// UnimplementedCodeAnalyzerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCodeAnalyzerServiceServer struct {
}

func (UnimplementedCodeAnalyzerServiceServer) HealthCheck(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedCodeAnalyzerServiceServer) mustEmbedUnimplementedCodeAnalyzerServiceServer() {}

// UnsafeCodeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeAnalyzerServiceServer will
// result in compilation errors.
type UnsafeCodeAnalyzerServiceServer interface {
	mustEmbedUnimplementedCodeAnalyzerServiceServer()
}

func RegisterCodeAnalyzerServiceServer(s grpc.ServiceRegistrar, srv CodeAnalyzerServiceServer) {
	s.RegisterService(&CodeAnalyzerService_ServiceDesc, srv)
}

func _CodeAnalyzerService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeAnalyzerServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/codeanalyzer.CodeAnalyzerService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeAnalyzerServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeAnalyzerService_ServiceDesc is the grpc.ServiceDesc for CodeAnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeAnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codeanalyzer.CodeAnalyzerService",
	HandlerType: (*CodeAnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _CodeAnalyzerService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "code-analyzer/code-analyzer.proto",
}
